M48
; DRILL file {KiCad (6.0.1)} date Thu Jun 23 18:29:58 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-23T18:29:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0197
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.2165
%
G90
G05
T1
X4.655Y-2.901
X5.028Y-2.898
T2
X5.475Y-3.241
X5.475Y-3.275
X5.475Y-3.309
T3
X4.766Y-5.197
X4.966Y-5.197
T4
X4.704Y-4.8718
X4.704Y-4.9718
X5.052Y-4.8658
X5.052Y-4.9658
T5
X4.854Y-2.093
T0
M30
