M48
; DRILL file {KiCad 7.0.2} date Sun May 28 20:46:51 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-28T20:46:51-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0492
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T6C0.2165
%
G90
G05
T1
X5.96Y-4.6969
X6.16Y-4.6969
T2
X5.996Y-4.991
X6.096Y-4.991
X6.327Y-4.677
X6.427Y-4.677
T3
X6.7835Y-5.4429
X6.8542Y-5.3722
T4
X5.3258Y-3.94
X5.3258Y-4.1171
X5.5817Y-3.94
X5.5817Y-4.1171
T5
X4.3572Y-3.0324
X4.9116Y-3.5896
T6
X3.556Y-2.212
T0
M30
