M48
; DRILL file {KiCad (6.0.1)} date Thu Jun 23 19:42:30 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-23T19:42:30-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0197
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.2165
%
G90
G05
T1
X5.296Y-4.325
X5.352Y-3.868
X5.685Y-3.915
X5.732Y-4.304
T2
X5.023Y-3.261
X5.057Y-3.261
X5.091Y-3.261
T3
X6.175Y-4.273
X6.375Y-4.273
T4
X5.996Y-4.991
X6.096Y-4.991
X6.327Y-4.677
X6.427Y-4.677
T5
X3.556Y-2.212
T0
M30
